# Generated by Django 2.0.2 on 2018-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('post_time', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
